server:
  port: 8081
example:
  loop: 11

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    connect-timeout: 6000

dubbo:
  registry:
    address: nacos://localhost:8848










