server:
  port: 8381
example:
  loop: 11

spring:
  profiles:
    active: dev
  cache:
    type: redis
#    type: SIMPLE

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    connect-timeout: 6000


dubbo:
  registry:
    address: nacos://localhost:8848










