server:
  port: 8001
  encoding:
    charset: UTF-8
spring:
  application:
#    本客户端在控制台展示名称
    name: myapp
  cloud:
    sentinel:
      # 持久化到nacos
      datasource:
        flow-rule:
          nacos:
            server-addr: localhost:8848
            group-id: SENTINEL_GROUP
            dataId: ${spring.application.name}-flow-rules
            data-type: json
            rule-type: flow
        degrade-rule:
          nacos:
            server-addr: localhost:8848
            group-id: SENTINEL_GROUP
            dataId: ${spring.application.name}-degrade-rules
            data-type: json
            rule-type: degrade
      # 链路模式未生效
      web-context-unify: false
      transport:
#        需要接入的控制台IP:地址
        dashboard: 127.0.0.1:8080
#        自定义本客户端接入端口，如果不指定会从8719自增尝试
        port: 8731
        eager: true
